title: "r3v::pwn"
description: "Reverse Engineering & Exploitation Research"
author: "g22_1"
baseurl: ""
url: "https://gjinikr.github.io"

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

highlighter: rouge
permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
